### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/ffsync_ynh#5]
Hi,

Your app doesn't work for the moment.
It's fail on the installation tests on our CI.
https://ci-apps.yunohost.org/jenkins/job/ffsync%20(Community)/5/consoleFull

Your app will be moved at 'notworking' status by the next week, on 15 of july.

**Comment by licryle** [comment]
Note that I've had issues with Yunohost 3.0, although it's still in experimental.
Turns out that the pip_install script is tweaked in Debian. I've fixed it manually with running:
pip install --ignore-installed --no-cache-dir pip

Before running:
yunohost app install https://github.com/YunoHost-Apps/ffsync_ynh --verbose

Might be useful in the future.

**Comment by Josue-T** [comment]
Should be fixed now.

Don't hesitate to reopen this issue if you encounter a new issue
